### PR TITLE
210914 Cuba 2019 JW

### PR DESCRIPTION
**Pull request by jianingwwww**
- As for formal health provider, I add médico pariente (doctor relative) and enfermera pariente (nurse relative) into the scope.
- As for formal health facility, I count CONSULTORIO DEL MÉDICO Y ENFERMERA DE LA FAMILIA (family doctor and nurse practitioners' office) in.

### CODE REVIEW

**Comment by robin-wang** [comment]
> * As for formal health provider, I add médico pariente (doctor relative) and enfermera pariente (nurse relative) into the scope.
> * As for formal health facility, I count CONSULTORIO DEL MÉDICO Y ENFERMERA DE LA FAMILIA (family doctor and nurse practitioners' office) in.

@jianingwwww Hey Jianing, when you have a chance, could you please upload Cuba raw data and output data files?

**Comment by robin-wang** [comment]
> * As for formal health provider, I add médico pariente (doctor relative) and enfermera pariente (nurse relative) into the scope.
> * As for formal health facility, I count CONSULTORIO DEL MÉDICO Y ENFERMERA DE LA FAMILIA (family doctor and nurse practitioners' office) in.

Per Table T.M. 4.1, I am inclined to include médico pariente (doctor relative) and enfermera pariente (nurse relative), which is what you did. Cuba definitions seem to be constructed based on a rather broad scope, that is to merely exclude Otro/Omitido for the consideration of Salud Calificado.

Table T.M 8.3 and Table TC. 3.1 both tend to view Consultario as a legitimate source of care. It should be noted that the treatment of Consultario is still unclear, even with Apendice A providing some information on the background of Consultario in Cuba.

**Comment by jianingwwww** [comment]
> > * As for formal health provider, I add médico pariente (doctor relative) and enfermera pariente (nurse relative) into the scope.
> > * As for formal health facility, I count CONSULTORIO DEL MÉDICO Y ENFERMERA DE LA FAMILIA (family doctor and nurse practitioners' office) in.
> 
> Per Table T.M. 4.1, I am inclined to include médico pariente (doctor relative) and enfermera pariente (nurse relative), which is what you did. Cuba definitions seem to be constructed based on a rather broad scope, that is to merely exclude Otro/Omitido for the consideration of Salud Calificado.
> 
> Table T.M 8.3 and Table TC. 3.1 both tend to view Consultario as a legitimate source of care. It should be noted that the treatment of Consultario is still unclear, even with Apendice A providing some information on the background of Consultario in Cuba.

Thank you for the suggestion! Do I still need to adjust the codes based on the very broad definition of Cuba, or leave it as is for now? I'll upload the results and data after we are finalized.

**Comment by robin-wang** [comment]
> > > * As for formal health provider, I add médico pariente (doctor relative) and enfermera pariente (nurse relative) into the scope.
> > > * As for formal health facility, I count CONSULTORIO DEL MÉDICO Y ENFERMERA DE LA FAMILIA (family doctor and nurse practitioners' office) in.
> > 
> > 
> > Per Table T.M. 4.1, I am inclined to include médico pariente (doctor relative) and enfermera pariente (nurse relative), which is what you did. Cuba definitions seem to be constructed based on a rather broad scope, that is to merely exclude Otro/Omitido for the consideration of Salud Calificado.
> > Table T.M 8.3 and Table TC. 3.1 both tend to view Consultario as a legitimate source of care. It should be noted that the treatment of Consultario is still unclear, even with Apendice A providing some information on the background of Consultario in Cuba.
> 
> Thank you for the suggestion! Do I still need to adjust the codes based on the very broad definition of Cuba, or leave it as is for now? I'll upload the results and data after we are finalized.

No changes needed in my view. It's basically confirming your treatments : )

**Review by wengxyu1030 — APPROVED** [review]

**Pull request merged**
