### PR TITLE
210921 update the subnational regions

### PR DESCRIPTION
**Pull request by jianingwwww**
- I have worked on the following 15 surveys in the raw data folder. Please tell me if there are any missing.
2f278538a9d590914c3b1edb0269e6d

### CODE REVIEW

**Comment by jianingwwww** [comment]
- There are some surveys that I have marked as "internal boundaries have changed" and I recorded them here.

- CentralAfricanRepublic
a2f10c63b0240fb549369102dfda0d0

- Nepal2019
16efb88f0ad21ff89b4ffdea6e743e9
2c59e6ef510ce48b4766cd3c47dfd11

- NorthMacedonia2019
716bd12a84f94960fabc5e100ed0615
421484761856da08903c75128aff1e6

- SaoTomeAndPrincipe2019
e5c3865c39afd60fd10e83a56ef8f35
2b1f36eea715b753338b2a47ba1e796

- Serbia2019
4a734ed35ad973b788597ee5c12e2b9
1914fa72341d73b9f4683dcf7241f60

- Thailand2019
0ece136d6937f20ed4ac4971851a325
ed2bb74651ee7855bc3d1dc06fdddf4

- StateofPalestine2019 （I have not coded it yet because I am not sure which gl_adm0_code should be used）
b6f75688731882d5ce026f782623cf7
417626e22682f67bbd3decb285e54a7
bc9594855d114924b4adfa504a6cf41

**Review by wengxyu1030 — APPROVED** [review]
Dear @jianingwwww ,

Thanks for your input, it looks fantastic. The issues are well documented, @robin-wang and I will look into them. No further questions on this pull request, I thereby merge it to the main branch. 

Regards, 
Aline

**Comment by robin-wang** [comment]
@jianingwwww Hey Jianing, I looked over your work and documentation, it's done with good clarity. Thanks! 
I checked against the data files we have here, wonder if you could also apply the same process onto Algeria2018?

**Comment by jianingwwww** [comment]
> @jianingwwww Hey Jianing, I looked over your work and documentation, it's done with good clarity. Thanks!
> I wonder if you could also apply the same process onto Algeria2018? My bad for missing Algeria's raw data; thanks for your understanding

Thank you for your reply! Please see #53 and please contact me if there are other questions. Bon week-end~

**Pull request merged**
